### ISSUE TITLE
unable to start site image after upgrade to 2.7.0

### ISSUE THREAD

**Issue by oiler** [10up/wp-local-docker-v2#108]
**Describe the bug**
I updated to Docker 2.2.0.4 and WP Local Docker 2.7.0 at the same time. Even after a full OS restart, i get the below error when trying to start an existing image:
```
ERROR: for 3bd937b7b045_global_mailcatcher_1  Cannot start service mailcatcher: Ports are not available: listen tcp 127.0.0.1:1025: bind: address already in use
```
Manually quitting the process seems to not fix the problem, the process is owned by "FinderSyn"

My short term fix is to rollback to wp-local-docker@2.6.2

**Steps to Reproduce**

**Expected behavior**
Everything else was working normally before the upgrades. 

**Screenshots**
https://www.dropbox.com/s/5269bytom7me8qz/Screenshot%202020-03-19%2011.07.07.png?dl=0

**Environment information**
 - Device: MB Pro 2018
 - OS: MacOS 10.14.6

**Additional context**
I've manually rolled back the 10up docker version back to 2.6.2 and it works again with that.

**Comment by esa1975** [comment]
I wasn't sure whether to open a new issue or add to this one but rolling back to 2.6.2 was also the fix for me. I wasn't able to connect to any sites or tools on 2.7.0 (unable to load site). I am running an Ubuntu 18.04 VM with virt-manager and have also tried with VirtualBox and saw the same thing. I'm not sure what to look for in order to provide meaningful feedback. If you'd like to have me test something or provide logs just let me know what you need. Thanks!

**Comment by dustinrue** [comment]
wp-local-docker expects to be the only dev environment running on the system. If you must support both at the same time you can update docker-compose.yml file located in ~/.wplocaldocker/global and remove the 127.0.0.1 from the port definition for mailcatcher
