### ISSUE TITLE
Migrating projects between machines / developers

### ISSUE THREAD

**Issue by samimakela** [10up/wp-local-docker-v2#191]
We're using 10updocker for local development, but we're not using wp-snapshots.

Until now we've added the entire directory created by ```10updocker create``` to version control, which has allowed us to share the whole project (including the local environment configuration) with other team members.

Since 2.8.0 creating a new project will add machine-specific information about the certifcate to the .config.json file, which causes problems when migrating the project to another machine.

Would very much appreciate advise on this one.

**Comment by eugene-manuilov** [comment]
@samimakela `2.8.0` has added the ability to create a configuration file for your project which should be added to your VCS instead of the whole environment. That config file is used in conjunction with `10updocker clone <git-url>` command to spin up a new environment with specific settings on a local machine.

You can see an example of a configuration file [here](https://github.com/eugene-manuilov/woocommerce/blob/edf664d97c5bf6a911ccb727d5848fba8aa320a6/wp-local-docker.config.js). As you can see there, it defines all settings for the new environment and even replaces memcached with redis. If you want to try it on your local machine, just run the following command:
```sh-session
10updocker clone git@github.com:eugene-manuilov/woocommerce.git
```

To create a new configuration file for your project, you need to run `10updocker init` command.

**Comment by samimakela** [comment]
Perfect! Thank you very much!
