### ISSUE TITLE
Impossible to create new websites

### ISSUE THREAD

**Issue by LucaPipolo** [10up/wp-local-docker-v2#312]
### Troubleshooting

- [X] I have attempted to troubleshoot this already

### Describe the bug

After a totally clean installation on a new machine (MacBook Pro 14'' M1 Pro) when I try to setup a new website using 10updocker create (does not matter what I choose in the following steps such as PHP version, WordPress installation, additional domains, etc.) I encounter the following errors:

1. The SSL certificate is not generated.
```
/bin/sh: /Users/lucapipolo/Library/Application: No such file or directory
⚠ Command failed: /Users/lucapipolo/Library/Application Support/fnm/node-versions/v16.16.0/installation/lib/node_modules/wp-local-docker/node_modules/mkcert-prebuilt/1.2.0.bin -CAROOT
/bin/sh: /Users/lucapipolo/Library/Application: No such file or directory 
```
2. The process never ends. It stuck forever on `Rewrite rules structure is updated to /%postname%/...` and never complete.

I already tried [the trouble shooting techniques](https://github.com/10up/wp-local-docker-v2#i-am-having-issues-with-wp-local-docker-what-are-the-best-troubleshooting-techniques) and did not help.

### Steps to Reproduce

1. Run `10updocker create`

### Screenshots, screen recording, code snippet

<img width="1507" alt="Schermata 2022-08-11 alle 20 24 34" src="https://user-images.githubusercontent.com/2393718/184211889-ca04aad1-a062-4028-beaa-9d1dbb8354e1.png">

### Environment information

MacBook Pro Model: MacBook Pro 18,3
Chip: Apple M1 Pro
Core Numbers: 8
RAM: 16 GB
macOS Monterey 12.3 (21E230)

Docker 4.11.1 (84025)
Engine: 20.10.17
Compose: 1.29.2
Kubernetes: v1.24.2

Node v.16.16.0
NPM 8.11.0
Installed using [FNM](https://github.com/Schniz/fnm)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LucaPipolo** [comment]
Not sure if this is related but I also now noticed that as well the delete process stuck forever ⬇️ 

<img width="556" alt="Schermata 2022-08-11 alle 20 50 09" src="https://user-images.githubusercontent.com/2393718/184216810-82c2d4cd-c3a5-42a7-9792-2b1fcbc4d613.png">

I'm not sure what `wp-local-docker-v2` is supposed to do on `/etc/hosts` (during troubleshooting procedure I read something about this) but I suspect is not working since I do not see any change to the file and I have to manually add the host there.

**Comment by mae829** [comment]
@LucaPipolo `wp-local-docker-v2` is trying to add/delete in `/etc/hosts` the necessary entry to recognize the custom URLs locally.
As far as your `1.` point, I had this happen using `fnm` as well and it's due to the installation location path. Specifically the space in `../Application Support/..` not being escaped by a command for `mkcert`.

My workaround was to move the whole folder `/Users/{your_user_name}/Library/Application Support/fnm` to the root `/Users/{your_user_name}/.fnm`.

Notes:
- Rename of the folder from `fnm` to `.fnm`.
- Had to set the default node version again with `fnm default {number}`.
- Quit the terminal and had to called `. ~/.zshrc`, might be a different file if you do not use Zsh (e.g. it might be `. ~/.bashrc` instead).

Hope that helps for you or anyone using `fnm` and it was installed via brew.
