### ISSUE TITLE
Increase memory limit

### ISSUE THREAD

**Issue by Fabiato** [10up/wp-local-docker-v2#86]
Hi,

How can I increase the php memory_limit? Maybe a php.ini to edit somewhere? 

Thanks

**Comment by dustinrue** [comment]
Each project created by wp-local-docker has a config directory. You'll find the file for php-fpm at `config/php-fpm/docker-php-ext-xdebug.ini`. This admittedly poorly named file is where you would want to change the memory limit.

**Comment by Fabiato** [comment]
Hi,

thank you for replying.

Cheers

**Comment by frankypixels** [comment]
Hi,
Can you idiot proof the documentation. Like "If you want to make changes to php.ini... do this, then that, then this." .. This file you mention doesn't make clear how to change settings like these:

max_execution_time
upload_max_filesize
post_max_size

It is not just like php.ini. If so adding the settings like so:

`max_execution_time = 360`
`upload_max_filesize = 256M`
`post_max_size = 256M`

Would simply work. I've started and restart docker, 10updocker, everything and nothing has changed. if I have to make changes elsewhere, I wouldn't know.

**Comment by benlk** [comment]
I'll see about getting this added to the docs, but this process worked for me today:

0. Navigate to the root directory of the install you want to make changes to.
1. Add your updated settings to `config/php-fpm/docker-php-ext-xdebug.ini`, as if it were `php.ini`
2. Run `10updocker stop all`
3. Run `10updocker start` to get this install and the global services running
4. Run `10updocker stop` to stop this install but not the global services
5. Run [`docker-compose up`](https://docs.docker.com/compose/reference/up/) to recreate and start this install's docker containers. Wait for it to finish starting; this can be determined by watching the console output. Don't load the site in a browser. If there hasn't been anything new on the console for at least 10 seconds, you can proceed to the next step.
6. Kill the newly-started docker process with `Control-C` or your system's equivalent.
7. Run `10updocker restart` to restart the container.
8. The settings specified should now apply.

There is a difference between restarting the container and recreating it; the simple `10updocker restart` doesn't apply settings changes.

**Comment by benlk** [comment]
@frankypixels I don't have an answer for you on that front, unfortunately.

**Comment by mae829** [comment]
Had to help someone with a similar issue so hope this helps.
The issue was increasing the upload size limit inside phpMyAdmin.
So the project specific settings weren't affecting the phpMyAdmin settings since it's a global setup.

1. Access the wplocal docker config by going to `~/.wplocaldocker/global/`
2. Open and edit the file `docker-composer.yml` file
3. The `phpmyadmin` environment config needs to be updated to include "UPLOAD_LIMIT: 300M" in line 58 (screenshot below to exactly where it should be in case config has different content)
4. Run `10updocker stop all && 10updocker start`
5. phpMyAdmin new upload limit should now be applied

This should not be limited to `UPLOAD_LIMIT` but it was the only one I had to set up.

![Screenshot 2023-06-08 at 2 53 56 PM](https://github.com/10up/wp-local-docker-v2/assets/11997449/58be4f1b-42d6-4df1-b4da-d1bfa7b6fa5c)
